export const POINTS_TO_REFILL = 10;

export const SUBSCRIPTION_PLANS_MONTHLY_POINTS = 5000;
export const SUBSCRIPTION_PLANS_YEARLY_POINTS = 30000;
export const SUBSCRIPTION_PLANS_LIFETIME_POINTS = 99999;
